// Code generated by "stringer -type transferStatus"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[transferStatusCreated-0]
	_ = x[transferStatusResolving-1]
	_ = x[transferStatusConnecting-2]
	_ = x[transferStatusDownloading-3]
	_ = x[transferStatusDone-4]
	_ = x[transferStatusError-5]
}

const _transferStatus_name = "transferStatusCreatedtransferStatusResolvingtransferStatusConnectingtransferStatusDownloadingtransferStatusDonetransferStatusError"

var _transferStatus_index = [...]uint8{0, 21, 44, 68, 93, 111, 130}

func (i transferStatus) String() string {
	if i >= transferStatus(len(_transferStatus_index)-1) {
		return "transferStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _transferStatus_name[_transferStatus_index[i]:_transferStatus_index[i+1]]
}
